// Data file path

var pitchtrack_t_default = "data/teacher/teacher_regression_pitchtrack.csv",
    pitchtrack_s_default = "data/example/student_regression_pitchtrack.csv",
    noteSeg_t_default = "data/teacher/teacher_monoNoteOut_midi.csv",
    noteSeg_s_default = "data/example/student_monoNoteOut_midi.csv",
    noteAlign_S2T_default = "data/example/student_noteAligned_example.csv",
    noteAlign_T2S_default = "data/teacher/teacher_noteAligned_example.csv",
    audio_t_default = "data/teacher/teacher.wav",
    audio_s_default = "data/example/student.wav",
    pitchtrack_t_update = "data/teacher/teacher_regression_pitchtrack.csv",    // Doesn't change
    pitchtrack_s_update = "data/student/student_regression_pitchtrack.csv",
    noteSeg_t_update = "data/teacher/teacher_monoNoteOut_midi.csv",
    noteSeg_s_update = "data/student/student_monoNoteOut_midi.csv",
    noteAlign_S2T_update = "data/student/student_noteAligned.csv",
    noteAlign_T2S_update = "data/teacher/teacher_noteAligned.csv",
    audio_t_update,
    audio_s_update = "data/student/student.wav",
    pitchSeg_t_default = "data/teacher/teacher_refinedSeg_example.csv",
    pitchSeg_s_default = "data/example/student_refinedSeg_example.csv",
    pitchSegAlign_T2S_default = "data/teacher/teacher_segAligned_example.csv",
    pitchSegAlign_S2T_default = "data/example/student_segAligned_example.csv",
    pitchSeg_t_update = "data/teacher/teacher_refinedSeg_example.csv",
    pitchSeg_s_update = "data/student/student_refinedSeg.csv",
    pitchSegAlign_T2S_update = "data/teacher/teacher_segAligned.csv",
    pitchSegAlign_S2T_update = "data/student/student_segAligned.csv";
